### ISSUE TITLE
High (very likely incorrect) temperatures detected

### ISSUE THREAD

**Issue by Deviad** [khronokernel/Getting-Started-With-OpenCore#11]
Hello,
with my motherboard (ASUS PRIME-Z370M-PLUS-II) I have experienced an issue whereby the temperature being shown for the CPU is 85. 
For this purpose I have used iStat Menus.
The BIOS shows a temperature of 30 degree.
Are the temperatures being displayed in Celsius or Fahrenheit?
Please note that when I have used Clover, the temperatures displayed by iStat Menus were correct.
However, maybe I should signal this issue to the author of virtualsmc.

**Comment by khronokernel** [comment]
Completely unrelated to this guide, you even say it yourself:
```
However, maybe I should signal this issue to the author of virtualsmc.
```
And also:
```
This guide has now been deprecated, for those who wish to follow a more up to date guide can follow the OpenCore Vanilla Desktop Guide
```
