### ISSUE TITLE
Could not enter BIOS after installing Open Core on primary NVME

### ISSUE THREAD

**Issue by Deviad** [khronokernel/Getting-Started-With-OpenCore#12]
Hello,
I would like to inform you that I installed successfully Open Core on my external USB flash drive with no issue, and all was fine except for the temperature issue that I reported in another thread.
However, after I installed Open Core in the EFI partition of my primary NVME (Samsung Evo 970), I could not get in the BIOS setup screen anymore.
I could only get into the boot loading sequence menu (the one you access by pressing F8) and access the hard drive. 
To solve the issue I had to reset the CMOS by linking the two pins described in the manual and take out the CMOS. After that, since neither this way the problem was solved, I had to install Windows and then use the BIOS flashing utility, which with I could install the latest BIOS version.
This finally fixed the issue.

**Comment by khronokernel** [comment]
I am not affiliated with OpenCore, and this guide has been deprecated for 4 months now. Please open up an issue in Acidanthera's bug tracker, not open issues here:
[Bug tracker](https://github.com/acidanthera/bugtracker)

```
This guide has now been deprecated, for those who wish to follow a more up to date guide can follow the OpenCore Vanilla Desktop Guide
```
