### ISSUE TITLE
Kernel Emulator/Emulation

### ISSUE THREAD

**Issue by Gigamaxx** [khronokernel/Getting-Started-With-OpenCore#5]
Could you please provide an example for CPU emulation (fake CPUID) for pentium CPUs.  We normally use 0x0306A0 (Ivy Bridge i5) as a fake ID.    This would be really helpful in the description below.    Also, NullCPUPowerManagementkext is often needed do you know if it's compatible?   Sorry to bother you, thanks for the Getting Started info.

**Comment by khronokernel** [comment]
Quote from Vit9696:
> Stuff like NullCPUPowerManagement is compatible, but is only needed on AMD.

And I will be adding some examples on spoofing for CPUs and just general clean up of the momentarily

**Comment by khronokernel** [comment]
@Gigamaxx Just added the section on emulation
