### ISSUE TITLE
help:I have a question about CustomSMBIOSGuid

### ISSUE THREAD

**Issue by melxman** [khronokernel/Getting-Started-With-OpenCore#8]
I have a dell inspiron 5448 laptop.
When I use clover, I need to use the dellsmbiospatch option to load my model information correctly.
Now I use oc boot, enter the system, kext load is no problem, but this model information is not complete.Just like"Macbookpro 15,"
When I read the pdf, I found that the description of the CustomSMBIOSGuid is for the dell laptops. And found that it is associated with UpdateSMBIOSMode, but I used the value of UpdateSMBIOSMode according to the description and found that Create enters the system normally, but the information is still incomplete; Custom or leave the system into the system, the time is very long and the model will become dell Actual model.
So let me ask for the proper use of this feature.

My English is not good. I am sorry, the above content is from Google Translate.

**Comment by khronokernel** [comment]
@melxman So I should start out with saying that this is **NOT** the official guide for Opencore and that I'm am not affiliated with Vit9696 or others in that project. I merely made this guide using previous knowledge and information provided in both the docs and the insanelymac forum.

Regarding your actual issue, what version of Opencore are you on? It'll also help to upload your EFI to help verify

**Comment by melxman** [comment]
> @melxman So I should start out with saying that this is **NOT** the official guide for Opencore and that I'm am not affiliated with Vit9696 or others in that project. I merely made this guide using previous knowledge and information provided in both the docs and the insanelymac forum.
> 
> Regarding your actual issue, what version of Opencore are you on? It'll also help to upload your EFI to help verify

I used 0.0.3 version。And thank you for your help.Please close this.
